[book]
authors = ["Ryan Marple"]
language = "en"
src = "src"
title = "CyderVis Documentation"

[build]
build-dir = "book"

[output.html]
additional-css = ["src/custom.css"]
site-url = "https://cyborg-dynamics-engineering.github.io/cyder-vis/"
use-absolute-links = true